_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
learning_rate:
    value:
        align: 0.5
        image: 0.0006
        text: 0.0006
lora:
    value:
        alpha: 1
        rank: 8
positive:
    value:
        alpha: 6
        beta: 5
        enabled: true
        shot_capacity: 3
