# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 3.0
  beta: 1.0 

learning_rate:
  text: 0.0002
  image: 0.0002
  align: 0.2