# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 7
  beta: 7.45 

learning_rate:
  text: 0.0006
  image: 0.0006
  align: 0.2