# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 6.0 
  beta: 5.0 
  low_rank:
    rank: 64  
  similarity_threshold: 0.9

learning_rate:
  text: 0.0003
  image: 0.0003
  align: 2.5