# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 2.5
  beta: 5.0 

learning_rate:
  text: 0.0001
  image: 0.0001
  align: 0.2