# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 4.0
  beta: 7.0 

learning_rate:
  text: 0.00005
  image: 0.00005
  align: 0.2