# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 9.0
  beta: 8.0 

learning_rate:
  text: 0.0004
  image: 0.0004
  align: 0.2